require("jonchines.plugins-setup")
require("jonchines.core.options")
require("jonchines.core.keymaps")
require("jonchines.core.colorscheme")
require("jonchines.plugins.toggleterm")
require("jonchines.plugins.comment")
require("jonchines.plugins.nvim-tree")
require("jonchines.plugins.lualine")
-- require("jonchines.plugins.bufferline")
require("jonchines.plugins.telescope")
require("jonchines.plugins.nvim-cmp")
require("jonchines.plugins.lsp.mason")
require("jonchines.plugins.lsp.lspsaga")
require("jonchines.plugins.lsp.lspconfig")
require("jonchines.plugins.lsp.null-ls")
require("jonchines.plugins.autopairs")
require("jonchines.plugins.treesitter")
require("jonchines.plugins.gitsigns")
require("jonchines.plugins.harpoon")
-- require("jonchines.plugins.fugitive")
require("jonchines.plugins.git")
require("jonchines.plugins.which-key")
require("jonchines.plugins.surround")
require("jonchines.plugins.ansible-vim")
